"""Structure des fiches DSF en tableaux.

Fichier généré par scripts/build_fiche_layouts.py à partir de
fiche_en_tableau/ouioui.xlsx. Ne pas modifier à la main : modifier le
classeur puis relancer le script.

Chaque fiche est une suite de tableaux ; chaque tableau a des colonnes et
des lignes (postes). Les valeurs sont rattachées dans l'ordre : ligne par
ligne, colonne par colonne. Une ligne « optional » n'existe que dans
certaines versions du fichier source.
"""

FICHE_LAYOUTS = {
    'IDENT': [
        {
            "title": None,
            "columns": ['Valeur'],
            "rows": [
                {'label': 'NUMERO DE LA DSF'},
                {'label': 'NUMERO DSF_T'},
                {'label': 'NIU'},
                {'label': 'Cle', 'optional': True},
                {'label': 'Raison sociale'},
                {'label': 'Sigle usuel'},
                {'label': "Catégorie de l'entreprise (Taille)"},
                {'label': "Catégorie de l'entreprise (Taille)"},
                {'label': 'Adresse'},
                {'label': 'Ville'},
                {'label': 'Ville'},
                {'label': 'Numero de téléphone'},
                {'label': 'Numéro de Téléphone 2'},
                {'label': 'e-mail'},
                {'label': 'Secteur Institutionnel'},
                {'label': 'Secteur Institutionnel'},
                {'label': 'Activité Principale'},
                {'label': 'Section'},
                {'label': 'Section'},
                {'label': "Branche d'activité"},
                {'label': "Branche d'activité"},
                {'label': "Sous-Branche d'activité"},
                {'label': "Sous-Branche d'activité"},
                {'label': 'Année'},
                {'label': 'Forme juridique'},
                {'label': 'Forme juridique'},
                {'label': "Nombre d'établissement dans le pays"},
                {'label': "Première année d'exercice dans le pays"},
                {'label': "Nombre d'activité"},
            ],
        },
    ],
    'BILAN_ACTIF': [
        {
            "title": None,
            "columns": ['BRUT', 'AMORT/DEPREC', 'NET_N', 'NET_N-1'],
            "rows": [
                {'label': 'IMMOBILISATIONS INCORPORELLES'},
                {'label': 'Frais de recherche et de prospection'},
                {'label': 'Brevets, Licences, Logiciels et droits similaires'},
                {'label': 'Fonds commercial et droit au bail'},
                {'label': 'Autres immobilisations incorporelles'},
                {'label': 'IMMOBILISATIONS CORPORELLES'},
                {'label': 'Terrains (Dont en placement)'},
                {'label': 'Bâtiments (Dont en placement)'},
                {'label': 'Aménagement, agencements et installations'},
                {'label': 'Matériel, mobilier et actif biologique'},
                {'label': 'Matériel de transport'},
                {'label': 'Avances et acompte versés sur immobilisations'},
                {'label': 'IMMOBILISATIONS FINANCIERES'},
                {'label': 'Titres de participations'},
                {'label': 'Autres immobilisations financières'},
                {'label': 'TOTAL ACTIF IMMOBILISE'},
                {'label': 'ACTIF CIRCULANT HAO'},
                {'label': 'STOCKS ET ENCOURS'},
                {'label': 'CEANCES ET EMPLOIS ASSIMILES'},
                {'label': 'Fournisseurs avances versées'},
                {'label': 'Clients'},
                {'label': 'Autres créances'},
                {'label': 'TOTAL ACTIF CIRCULANT'},
                {'label': 'Titres de placement'},
                {'label': 'Valeurs à encaisser'},
                {'label': 'Banques, chèques postaux, caisse'},
                {'label': 'TOTAL TRESORERIE ACTIF'},
                {'label': 'Ecart de conversion-actif'},
                {'label': 'TOTAL GENERAL'},
            ],
        },
    ],
    'BILAN_PASSIF': [
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Capital NET'},
                {'label': 'Apporteurs capital non appelé'},
                {'label': 'Primes liées capital social'},
                {'label': 'Ecarts de réévaluation'},
                {'label': 'Réserves indisponibles'},
                {'label': 'Réserves libres'},
                {'label': 'Report à nouveau (+ou-)'},
                {'label': "Résultat net de l'exercice (+ou-)"},
                {'label': "Subventions d'investissement"},
                {'label': 'Provisions réglementées'},
                {'label': 'TOTAL CAPITAUX PROPRES ET RESSOURCES ASSIMILEES'},
                {'label': 'Emprunts et dettes financières diverses'},
                {'label': 'Dettes de location acquisition'},
                {'label': 'Provisions pour risques et charges'},
                {'label': 'TOTAL DETTES FINANCIERES ET RESSOURCES ASSIMILEES'},
                {'label': 'TOTAL RESSOURCES STABLES'},
                {'label': 'Dettes circulantes HAO'},
                {'label': 'Clients, avances reçues'},
                {'label': "Fournisseurs d'exploitations"},
                {'label': 'Dettes fiscales et sociales'},
                {'label': 'Autres dettes'},
                {'label': 'Provisions pour risques à court terme'},
                {'label': 'TOTAL PASSIF CIRCULANT'},
                {'label': "Banques, crédits d'escomptes"},
                {'label': 'Banques, établissements financièrs et crédit de trésorerie'},
                {'label': 'TOTAL TRESORERIE-PASSIF'},
                {'label': 'Ecart de conversion-passif'},
                {'label': 'TOTAL GENERAL PASSIF'},
            ],
        },
    ],
    'COMPTE_RESULTAT': [
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'TA Ventes de marchandises'},
                {'label': 'RA Achats de marchandises'},
                {'label': 'RB Variation de stocks de marchandise'},
                {'label': 'XA MARGES COMMERCIALES'},
                {'label': 'TB Ventes de produits fabriqués'},
                {'label': 'TC travaux et services vendus'},
                {'label': 'TD Produits accessoires'},
                {'label': "XB CHIFFRE D'AFFAIRES"},
                {'label': 'TE Production stockée ou déstockée'},
                {'label': 'TF Production immobilisée'},
                {'label': "TG Subventions d'exploitation"},
                {'label': 'TH Autres produits'},
                {'label': "TI Transferts de charges d'exploitation"},
                {'label': 'RC Achats de MP et fournitures liées'},
                {'label': 'RD Variations de stocks de MP et fourn. liées'},
                {'label': 'RE Autres achats'},
                {'label': "RF Variations de stocks d'autres approvisionnement"},
                {'label': 'RG Transports'},
                {'label': 'RH Services extérieurs'},
                {'label': 'RI Impôts et taxes'},
                {'label': 'RJ Autres charges'},
                {'label': 'XC VALEUR AJOUTEE'},
                {'label': 'RK Charges de personnel'},
                {'label': "XD EXCEDENT BRUT D'EXPLOITATION"},
                {'label': "TJ Reprises d'amortissements, provisions et dépréciations"},
                {'label': 'RL Dotations aux amortissements, aux provisions et aux dépréciations'},
                {'label': "XE RESULTAT D'EXPLOITATION"},
                {'label': 'TK Revenus financiers et assimilés'},
                {'label': 'TL Reprises de provisions et dépréciations financières'},
                {'label': 'TM Transferts de charges financières'},
                {'label': 'RM Frais financiers et charges assimilées'},
                {'label': 'RN Dotations aux provisions et aux dépréciations financières'},
                {'label': 'XF RESULTAT FINANCIER'},
                {'label': 'XG RESULTAT DES ACTIVITES ORDINAIRES (1)'},
                {'label': "TN Produits des cessions d' immobilisations"},
                {'label': 'TO Autres Produits HAO'},
                {'label': "RO Valeur comptable des cessions d' immobilisations"},
                {'label': 'RP Autres Charges HAO'},
                {'label': 'XH RESULTAT HORS ACTIVITE ORDINAIRE (HAO)'},
                {'label': 'RQ Participation des travailleurs'},
                {'label': 'RS Impôts sur le résultat'},
                {'label': 'XI RESULTAT NET'},
            ],
        },
    ],
    'NOTE_3A': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['MONT_BRUT_OUVERT', 'ACQUIST_APPORT_CREAT', 'VIREMENT_POSTE_POSTE', 'REEVALUATION', 'CESSIONS_SCISSIONS', 'VIREMENT_POSTE_POSTE', 'MONT_BRUT_CLOTURE'],
            "rows": [
                {'label': 'AD IMMOBILISATION INCORPORELLES'},
                {'label': 'AE Frais de développement et de prospection'},
                {'label': 'AF Brevets, licences, logiciels et droits assimilés'},
                {'label': 'AG Fonds commercial et droit au bail'},
                {'label': 'AH Autres immobilisations incorporelles'},
                {'label': 'AI IMMOBILISATIONS CORPORELLES'},
                {'label': 'AJ Terrains hors immeuble de placement'},
                {'label': 'AJ Terrains - immeuble de placement'},
                {'label': 'AK Batiments hors immeuble de placement'},
                {'label': 'AK Batiments - immeuble de placement'},
                {'label': 'AL Installations et agencements'},
                {'label': 'AM Matériel'},
                {'label': 'AN Matériel de transport'},
                {'label': 'AVANCES ET ACOMPTES VERSES SUR IMMOBILISATIONS'},
                {'label': 'Immobilisations Incorporelles'},
                {'label': 'Immobilisations corporelles'},
                {'label': 'IMMOBILISATIONS FINANCIERES'},
                {'label': 'Titres de participation'},
                {'label': 'Autres immobilisations financières'},
                {'label': 'TOTAL GENERAL'},
            ],
        },
        {
            "title": 'Note 3C',
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?', 'optional': True},
            ],
        },
        {
            "title": None,
            "columns": ['AMORT_CUMUL_OUVERTURE', 'AUGMENTATIONS_DOTATIONS', 'DIMUNITIONS_AMORT_RELATIF …', 'CUMUL_AMORT_CLOTURE'],
            "rows": [
                {'label': 'AE Frais de recherche et de développement'},
                {'label': 'AF Brevets, licences, logiciels'},
                {'label': 'AG Fonds commercial'},
                {'label': 'AH Autres immobilisations incorporelles'},
                {'label': 'TOTAL'},
                {'label': 'AJ Terrains hors immeuble de placement'},
                {'label': 'AJ Terrains - immeuble de placement'},
                {'label': 'AK Batiments hors immeuble de placement'},
                {'label': 'AK Batiments - immeuble de placement'},
                {'label': 'AL Installations et agencements'},
                {'label': 'AM Matériel'},
                {'label': 'AN Matériel de transport'},
                {'label': 'TOTAL'},
                {'label': 'TOTAL GENERAL'},
            ],
        },
    ],
    'NOTE_AMORT': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['AMORT_CUMUL_OUVERTURE', 'AUGMENTATIONS_DOTATIONS', 'DIMUNITIONS_AMORT_RELATIF …', 'CUMUL_AMORT_CLOTURE'],
            "rows": [
                {'label': 'AE Frais de recherche et de développement'},
                {'label': 'AF Brevets, licences, logiciels'},
                {'label': 'AF Brevets, licences, logiciels'},
                {'label': 'AG Fonds commercial'},
                {'label': 'AH Autres immobilisations incorporelles'},
                {'label': 'AD IMMOBILISATION INCORPORELLES'},
                {'label': 'AJ Terrains'},
                {'label': 'AJ Terrains'},
                {'label': 'AK Batiments'},
                {'label': 'AL Installations et agencements'},
                {'label': 'AM Matériel'},
                {'label': 'AN Matériel de transport'},
                {'label': 'AN Matériel de transport'},
                {'label': 'AI IMMOBILISATIONS CORPORELLES'},
                {'label': 'Titres de participation'},
                {'label': 'Autres immobilisations financières'},
                {'label': 'IMMOBILISATIONS FINANCIERES'},
                {'label': 'IMMOBILISATIONS FINANCIERES'},
            ],
        },
        {
            "title": None,
            "columns": ['AUGMENTATIONS_DOTATIONS', 'DIMUNITIONS_AMORT_RELATIF …', 'CUMUL_AMORT_CLOTURE'],
            "rows": [
                {'label': 'TOTAL GENERAL'},
            ],
        },
    ],
    'NOTE_4': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1', 'CRÉANCE_À_1_AN_AU_PLUS', 'CRÉANCE_À_PLUS_D1_ET_A_2ANS_AU_PLUS', 'CRÉANCE_À_PLUS_DE _2ANS'],
            "rows": [
                {'label': 'Titres de participation'},
                {'label': 'Prêts et créances'},
                {'label': 'Prêt au personnel'},
                {'label': "Créances sur l'Etat"},
                {'label': 'Titres immobilisés'},
                {'label': 'Dépôts et cautionnements'},
                {'label': 'Intérêts courus'},
                {'label': 'Immobilisations finacières diverses'},
                {'label': 'TOTAL BRUT'},
                {'label': 'Dépréciations des titres de participations'},
                {'label': 'Dépréciations autres immobilisations'},
                {'label': 'TOTAL NET DE DEPRECIATIONS'},
            ],
        },
    ],
    'NOTE_5_ACTIF': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': "Créances sur cessions d'immobilisations"},
                {'label': 'Autres créances HAO'},
                {'label': 'TOTAL BRUT'},
                {'label': 'Dépréciation des créances HAO'},
                {'label': 'TOTAL NET DE DEPRECIATION'},
            ],
        },
    ],
    'NOTE_5_PASSIF': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': "Fournisseurs d'investissements"},
                {'label': "Fournisseurs d'investissements effets à payer"},
                {'label': 'Versements restant à effectuer sur titres de participation et titres immobilisés non libérés'},
                {'label': 'Autres dettes hors activités ordinaires'},
                {'label': 'TOTAL'},
            ],
        },
    ],
    'NOTE_6': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Marchandises'},
                {'label': 'Matières première et fournitures liées'},
                {'label': 'Autres approvisionnements'},
                {'label': 'Produits en-cours'},
                {'label': 'Services en-cours'},
                {'label': 'Produits finis'},
                {'label': 'Produits intermediaires'},
                {'label': 'Stocks en-cours de routes, en consignation ou en dépôt'},
                {'label': 'TOTAL BRUT'},
                {'label': 'Dépréciations des stocks'},
                {'label': 'TOTAL NET DE DEPRECIATIONS'},
            ],
        },
    ],
    'NOTE_7': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1', 'CRÉANCE_À_1_AN_AU_PLUS', 'CRÉANCE_À_PLUS_D1_ET_A_2ANS_AU_PLUS', 'CRÉANCE_À_PLUS_DE _2ANS'],
            "rows": [
                {'label': 'Clients (Hors réserves de propriété et Groupe)'},
                {'label': 'Clients et effets à recevoir avec réserves de propriété'},
                {'label': 'Clients et effets à recevoir Groupe'},
                {'label': "Créances sur cession d'immobilisations"},
                {'label': 'Clients effets escompté et non échus'},
                {'label': 'Créances litigieuses ou douteuses'},
                {'label': 'Clients produits recevoir'},
                {'label': 'TOTAL BRUTS CLIENTS'},
                {'label': 'Dépréciations des comptes clients'},
                {'label': 'TOTAL NET DE DEPRECIATIONS'},
                {'label': 'Clients, avances reçues hors groupe'},
                {'label': 'Clients, avances reçues groupe'},
                {'label': 'Autres clients créditeurs'},
                {'label': 'TOTAL CLIENTS CREDITEURS'},
            ],
        },
    ],
    'NOTE_8': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1', 'CRÉANCE_À_1_AN_AU_PLUS', 'CRÉANCE_À_PLUS_D1_ET_A_2ANS_AU_PLUS', 'CRÉANCE_À_PLUS_DE _2ANS'],
            "rows": [
                {'label': 'Personnel'},
                {'label': 'Organismes sociaux'},
                {'label': 'Etat et collectivités publiques'},
                {'label': 'Organisations internternationaux'},
                {'label': 'Apporteurs, associés et groupe'},
                {'label': 'Compte transitoire ajustement spécial lié à la révision du SYSCOHADA'},
                {'label': 'Autres débiteurs divers'},
                {'label': 'Comptes permanents non bloqués des établissements et des succursales'},
                {'label': 'Comptes de liaison charges et produits'},
                {'label': 'Comptes de liaison des sociétés en participation'},
                {'label': 'TOTAL BRUT DES AUTRES CREANCES'},
                {'label': 'Dépréciations des autres créances'},
                {'label': 'TOTAL NET DE DEPRECIATIONS'},
            ],
        },
    ],
    'NOTE_9': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Titres de trésor et bons de caisse à court terme'},
                {'label': 'Actions'},
                {'label': 'Obligations'},
                {'label': 'Bons négociables hors régions'},
                {'label': 'Intérêts courus'},
                {'label': 'Autres valeurs assimilés'},
                {'label': 'TOTAL BRUT TITRES'},
                {'label': 'Dépréciations des titres'},
                {'label': 'TOTAL NET DE DEPRECIATIONS'},
            ],
        },
    ],
    'NOTE_10': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Effets à encaisser'},
                {'label': "Effets à l'encaissement"},
                {'label': 'Chèques à encaisser'},
                {'label': "Chèques à l'encaissement"},
                {'label': 'Carte de crédit à encaisser'},
                {'label': 'Autres valeurs à encaisser'},
                {'label': 'TOTAL BRUT VALEURS A ENCAISSER'},
                {'label': 'Dépréciations de valeurs à encaisser'},
                {'label': 'TOTAL NET DE DEPRECIATIONS'},
            ],
        },
    ],
    'NOTE_11': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Banques locales'},
                {'label': 'Banques autres états région'},
                {'label': 'Banques, dépôt à terme'},
                {'label': 'Autres banques'},
                {'label': 'Banques intérêt courus'},
                {'label': 'Chèques postaux'},
                {'label': 'Autres établissements financiers'},
                {'label': 'Etablissements financiers intérêts courus'},
                {'label': 'Instruments de trésorerie'},
                {'label': 'Caisse'},
                {'label': 'Caisse électronique mobile'},
                {'label': "Régies d'avances et virements accréditifs"},
                {'label': 'TOTAL : BRUT DISPONIBILITES'},
                {'label': 'Dépréciations'},
                {'label': 'TOTAL NET DE DEPRECIATIONS'},
            ],
        },
    ],
    'NOTE_14': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': "Prime d'apport"},
                {'label': "Prime d'émission"},
                {'label': 'Prime de fusion'},
                {'label': 'Prime de conversion'},
                {'label': 'Autres primes'},
                {'label': 'TOTAL : PRIMES'},
                {'label': 'Réserves légales'},
                {'label': 'Réserves statutaires'},
                {'label': 'Réserves de plus-values nettes à long terme'},
                {'label': "Réserves d'attribution gratuite d'actions au personnel"},
                {'label': 'Autres réserves réglementées'},
                {'label': 'TOTAL : RESERVES INDISPONIBLES'},
                {'label': 'Réserves libres'},
                {'label': 'Report à nouveau'},
            ],
        },
    ],
    'NOTE_15A': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Etat'},
                {'label': 'Département (Région)'},
                {'label': 'Communes et collectivités publiques décentralisées'},
                {'label': 'Entités publiques ou mixtes'},
                {'label': 'Entités et organismes privés'},
                {'label': 'Organismes internationaux'},
                {'label': 'TOTAL SUBVENTIONS'},
                {'label': 'Amortissements dérogatoires'},
                {'label': 'Plus-value de cession à réinvestir'},
                {'label': 'Provisions spéciales de réevaluation'},
                {'label': 'Provisions réglementées relatives aux immobilisations'},
                {'label': 'Provisions réglementées relatives aux stocks'},
                {'label': 'Provisions pour investissement'},
                {'label': 'Autres provisions et fonds réglementées'},
                {'label': 'TOTAL : PROVISIONS REGLEMENTEES'},
                {'label': 'TOTAL GENERAL'},
            ],
        },
    ],
    'NOTE_15B': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1', 'DETTE_À_1_AN_AU_PLUS', 'DETTE_À_PLUS_D1_ET_A_2ANS_AU_PLUS', 'DETTE_À_PLUS_DE _2ANS'],
            "rows": [
                {'label': 'Titres participatifs'},
                {'label': 'Avances conditionnées'},
                {'label': 'Titres subordonnées à durée indéterminés (TSDI)'},
                {'label': 'Obligations remboursables en actions (ORA)'},
                {'label': 'Autres'},
                {'label': 'TOTAL AUTRES FONDS PROPRES'},
            ],
        },
    ],
    'NOTE_16A': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1', 'DETTE_À_1_AN_AU_PLUS', 'DETTE_À_PLUS_D1_ET_A_2ANS_AU_PLUS', 'DETTE_À_PLUS_DE _2ANS'],
            "rows": [
                {'label': 'Emprunts obligatoires'},
                {'label': 'Emprunts et dettes auprès des établissements de crédit'},
                {'label': "Avances reçues de l'Etat"},
                {'label': 'Avances reçues et comptes courants bloqués'},
                {'label': 'Dépots et cautionnements reçus'},
                {'label': 'Interets courus'},
                {'label': 'Avances assorties de conditions particulières'},
                {'label': 'Autres emprunts et dettes'},
                {'label': 'Dettes liées à des participations'},
                {'label': 'Comptes permanents bloqués des établissements et succursales'},
                {'label': 'crédit-bail immobilier'},
                {'label': 'Total crédit-bail mobilier'},
                {'label': 'Total location-vente'},
                {'label': 'Total interets courus'},
                {'label': 'Total autres dettes de locations'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Total provisions pour litiges'},
                {'label': 'Total provisions pour garantie donnés aux clients'},
                {'label': 'Total provisions pour pertes sur marchés à achevement futur'},
                {'label': 'Total Provisions pour pertes de change'},
                {'label': 'Total provisions pour impots'},
                {'label': 'Total provisions pour pensions et obligations similaires'},
                {'label': 'Total actif du regime de retraite'},
                {'label': 'Total provisions pour restructuration'},
                {'label': 'Total provisions pour amendes et provisions'},
                {'label': 'Total provisions pour propre'},
                {'label': 'Total provisions pour dementelement'},
                {'label': 'Total provisions de droits à reduction'},
                {'label': 'autres provisions'},
                {'label': 'TOTAL EMPRUNTS ET DETTES FINANCIERES'},
                {'label': 'TOTAL EMPRUNTS ET DETTES FINANCIERES'},
                {'label': 'TOTAL EMPRUNTS ET DETTES FINANCIERES'},
                {'label': 'TOTAL DETTES DE LOCATION ACQUISITION'},
                {'label': 'TOTAL DETTES DE LOCATION ACQUISITION'},
                {'label': 'TOTAL PROVISIONS POUR RISQUES ET CHARGES'},
            ],
        },
    ],
    'NOTE_16B': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': "Taux d'augmentation des salaires"},
                {'label': "Taux d'actualisation"},
                {'label': "Taux d'inflation"},
                {'label': "Proba d'être à l'entité à la date de depart à la retraite"},
                {'label': "Proba d'être en vue à l'âge de depart à la retraite"},
                {'label': 'Taux de rendement effectif des actifs du régime'},
                {'label': "Obligations au titre des engagements de retraite à l'ouverture"},
                {'label': "Couts de services rendus au cours de l'exercice"},
                {'label': 'Couts financiers'},
                {'label': 'Pertes actuarielles'},
                {'label': 'Prestations payées'},
            ],
        },
        {
            "title": None,
            "columns": ['N AUGMENTATION', 'N DIMINUTION', 'N-1 AUGMENTATION', 'N-1 DIMINUTION'],
            "rows": [
                {'label': 'Obligations au titre des engagements de retraite à la fermeture'},
                {'label': "Taux d'actualisation (variation)"},
                {'label': 'Taux de progression'},
            ],
        },
        {
            "title": None,
            "columns": ['N AUGMENTATION', 'N DIMINUTION'],
            "rows": [
                {'label': 'Taux de depart du personnel'},
            ],
        },
    ],
    'NOTE_17': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1', 'DETTE_À_1_AN_AU_PLUS', 'DETTE_À_PLUS_D1_ET_A_2ANS_AU_PLUS', 'DETTE_À_PLUS_DE _2ANS'],
            "rows": [
                {'label': 'Fournisseurs dettes en compte (hors groupe)'},
                {'label': 'Fournisseurs effets à payer (hors groupe)'},
                {'label': 'Fournisseurs, dettes et effets à payer (groupe)'},
                {'label': 'Fournisseurs factures non parvenues (hors groupe)'},
                {'label': 'Fournisseurs factures non parvenues (groupe)'},
                {'label': 'TOTAL : FOURNISSEURS'},
                {'label': 'Fournisseurs, avances et acomptes (Hors groupe)'},
                {'label': 'Fournisseurs, avances et acomptes (Groupe)'},
                {'label': 'Autres fournisseurs débiteurs'},
                {'label': 'TOTAL : FOURNISSEURS DEBITEURS'},
            ],
        },
    ],
    'NOTE_18': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1', 'DETTE_À_1_AN_AU_PLUS', 'DETTE_À_PLUS_D1_ET_A_2ANS_AU_PLUS', 'DETTE_À_PLUS_DE _2ANS'],
            "rows": [
                {'label': 'Personnel avances et acomptes'},
                {'label': 'Personnels rémunérations dues'},
                {'label': 'Autres personnels'},
                {'label': 'Sécurité sociale (CNSS)'},
                {'label': 'Caisse de retraite'},
                {'label': 'Autres organismes sociaux'},
                {'label': 'TOTAL DETTES SOCIALES'},
                {'label': 'Etat, impôts sur les bénéfices'},
                {'label': 'Etat, impôts et taxes'},
                {'label': 'Etat, TVA'},
                {'label': 'Etat, impôts retenus à la source'},
                {'label': 'Autres dettes Etat'},
                {'label': 'TOTAL : DETTES FISCALES'},
                {'label': 'TOTAL : DETTES SOCIALES ET FISCALES'},
            ],
        },
    ],
    'NOTE_19': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1', 'DETTE_À_1_AN_AU_PLUS', 'DETTE_À_PLUS_D1_ET_A_2ANS_AU_PLUS', 'DETTE_À_PLUS_DE _2ANS'],
            "rows": [
                {'label': 'Organismes internationaux'},
                {'label': 'Apporteurs, Opérations sur Capital'},
                {'label': 'Associés, compte courant'},
                {'label': 'Associés, dividendes à payer'},
                {'label': 'Groupe, comptes courants'},
                {'label': 'Autres dettes associés'},
                {'label': 'TOTAL DETTES ASSOCIES'},
                {'label': 'Créditeurs divers'},
                {'label': 'Obligataires'},
                {'label': "Rémunérations d'administrateurs"},
                {'label': 'Compte du factor'},
                {'label': 'Versement restant à effectuer sur titres de placement'},
                {'label': 'Compte transitoire ajustement spécial lié à la révision de SYSCOHADA'},
                {'label': 'Autres créditeurs divers'},
                {'label': 'TOTAL : CREDITEURS DIVERS'},
                {'label': 'Comptes permanent non bloqués des établissements et des succursales'},
                {'label': 'Comptes de liaisons charges et produits'},
                {'label': 'Comptes de liaisons des sociétés en participation'},
                {'label': 'TOTAL : COMPTES DE LIAISON'},
                {'label': 'TOTAL : AUTRES DETTES'},
            ],
        },
    ],
    'NOTE_20': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Escomptes de crédit de campagne'},
                {'label': 'Escomptes de crédit ordinaires'},
                {'label': "TOTAL : CREDIT D'ESCOMPTE"},
                {'label': 'Banques Locales'},
                {'label': 'Banques autres états région'},
                {'label': 'Autres banques'},
                {'label': 'Banques inêtréts courus'},
                {'label': 'Crédit de trésorerie'},
                {'label': 'Crédit de trésorerie inêtréts courus'},
                {'label': 'TOTAL : BANQUES ET CREDIT DE TRESORERIE'},
                {'label': 'TOTAL GENERAL'},
            ],
        },
    ],
    'NOTE_21': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Ventes dans la région'},
                {'label': 'Ventes hors région'},
                {'label': 'Ventes groupe'},
                {'label': 'Ventes sur internet'},
                {'label': 'Rabais, remises, ristournes accordés (non ventilés)'},
                {'label': 'TOTAL : VENTES DE MARCHANDISES'},
                {'label': 'Ventes dans la région'},
                {'label': 'Ventes hors région'},
                {'label': 'Ventes groupe'},
                {'label': 'Ventes sur internet'},
                {'label': 'Rabais, remises, ristournes accordés (non ventilés)'},
                {'label': 'TOTAL : VENTES DE PRODUITS FABRIQUES'},
                {'label': 'Ventes dans la région'},
                {'label': 'Ventes hors région'},
                {'label': 'Ventes groupe'},
                {'label': 'Ventes sur internet'},
                {'label': 'Rabais, remises, ristournes accordés (non ventilés)'},
                {'label': 'TOTAL : TRAVAUX ET SERVICE VENDUS'},
                {'label': 'Services vendus'},
                {'label': 'Produits accessoires'},
                {'label': "TOTAL : CHIFFRE D'AFFAIRES"},
                {'label': 'Production immobilisée'},
                {'label': "Subvention d'exploitation"},
                {'label': 'Autres produits'},
                {'label': 'TOTAL : AUTRES PRODUITS'},
                {'label': 'TOTAL GENERAL'},
            ],
        },
    ],
    'NOTE_22': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Achats de marchandises dans la région'},
                {'label': 'Achats de marchandises hors dans la région'},
                {'label': 'Achats de marchandises groupe'},
                {'label': 'Frais sur achats'},
                {'label': 'Rabais, remises, ristournes obtenus (non ventilés)'},
                {'label': 'TOTAL : Achats de marchandises'},
                {'label': 'Achats de matières premières et fournitures liées dans la région'},
                {'label': 'Achats de matières premières et fournitures liées hors région'},
                {'label': 'Achats groupe de matières premières et fournitures liées'},
                {'label': 'Frais sur achats'},
                {'label': 'Rabais, remises, ristournes accordés (non ventilés)'},
                {'label': 'TOTAL : Achats de matières premières et fournitures liées'},
                {'label': 'Matières consommables'},
                {'label': 'Matières combustibles'},
                {'label': "Produits d'entretien"},
                {'label': "Fournitures d'atelier, d'usine et de magasin"},
                {'label': 'Eau'},
                {'label': 'Electricité'},
                {'label': 'Autres énergies'},
                {'label': "Fournitures d'entretien"},
                {'label': 'Fournitures de bureau'},
                {'label': 'Petit matériel et outillage'},
                {'label': 'Achats études, prestations de services, de travaux, matériels et équipements'},
                {'label': "Achats d'emballages"},
                {'label': 'Frais sur achats'},
                {'label': 'Rabais, remises et ristournes obtenus'},
                {'label': 'TOTAL : Autres Achats'},
                {'label': 'TOTAL GENERAL'},
            ],
        },
    ],
    'NOTE_23': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Transports sur ventes'},
                {'label': 'Transport pour le compte de tiers'},
                {'label': 'Transport du Personnel'},
                {'label': 'Transport de plis'},
                {'label': 'Autres Transports'},
                {'label': 'Total Transports'},
            ],
        },
    ],
    'NOTE_24': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Sous-traitance générale'},
                {'label': 'Locations et charges locatives'},
                {'label': 'Redevances de location acquisition'},
                {'label': 'Entretien, réparations et maintenance'},
                {'label': "Primes d'Assurances"},
                {'label': 'Etude, recherche et documentation'},
                {'label': 'Publicité, publications, relations publiques'},
                {'label': 'Frais de télécommunication'},
                {'label': 'Frais bancaires'},
                {'label': "Rémunérations d'intermédiaires et de conseil"},
                {'label': 'Frais de formation du personnel'},
                {'label': 'Redevances pour brevets, licences, logiciels concessions et droit similaires'},
                {'label': 'Cotisations'},
                {'label': 'Autres charges externes'},
                {'label': 'TOTAL SERVICE EXTERNE'},
            ],
        },
    ],
    'NOTE_25': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Impôts et taxes directs'},
                {'label': 'Impôts et taxes indirects'},
                {'label': "Droits d'enregistrement"},
                {'label': 'Pénalités et amendes fiscales'},
                {'label': 'Autres Impôts et taxes'},
                {'label': 'TOTAL'},
            ],
        },
    ],
    'NOTE_26': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Pertes sur créances clients'},
                {'label': 'Pertes sur autres débiteurs'},
                {'label': 'Quote-part de résultat sur opérations faites en commun'},
                {'label': "Valeur comptable des cessions courantes d'immobilisations"},
                {'label': 'Pertes de changes sur créances et dettes commerciales'},
                {'label': 'Pénalités et amendes fiscales'},
                {'label': "Indemnités de fonction et autres rémunérations d'adminisrateurs"},
                {'label': 'Dons et mécenat'},
                {'label': 'Autres charges diveres'},
                {'label': "Charges pour provisions et provisions pour risque à court terme d'exploitation"},
                {'label': 'TOTAL : AUTRES CHARGES'},
            ],
        },
    ],
    'NOTE_27A': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Rémunérations directes versées au personnel'},
                {'label': 'Indémnités forfaitaires versées au personnel'},
                {'label': 'Charges Sociales'},
                {'label': "Rémunérations et charges sociales de l'exploitant individuel"},
                {'label': 'Rémunérations transférées de personnel extérieur'},
                {'label': 'Autres Charges Sociales'},
                {'label': 'TOTAL'},
            ],
        },
    ],
    'NOTE_27B': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['HOMME', 'FEMME', 'TOTAL'],
            "rows": [
                {'label': 'Cadres supérieurs – Effectif'},
                {'label': 'Techniciens supérieurs et cadres moyens – Effectif'},
                {'label': 'Techniciens, agents de maîtrise et ouvriers qualifiés – Effectif'},
                {'label': 'Employés, manœuvres, ouvriers et apprentis – Effectif'},
                {'label': 'TOTAL (1)'},
                {'label': 'Cadres supérieurs – Masse salariale'},
                {'label': 'Techniciens supérieurs et cadres moyens – Masse salariale'},
                {'label': 'Techniciens, agents de maîtrise et ouvriers qualifiés – Masse salariale'},
                {'label': 'Employés, manœuvres, ouvriers et apprentis – Masse salariale'},
                {'label': 'TOTAL (1)'},
                {'label': 'Cadres supérieurs – Effectif'},
                {'label': 'Techniciens supérieurs et cadres moyens – Effectif'},
                {'label': 'Techniciens, agents de maîtrise et ouvriers qualifiés – Effectif'},
                {'label': 'Employés, manœuvres, ouvriers et apprentis – Effectif'},
                {'label': 'TOTAL (2)'},
                {'label': 'Cadres supérieurs – Masse salariale'},
                {'label': 'Techniciens supérieurs et cadres moyens – Masse salariale'},
                {'label': 'Techniciens, agents de maîtrise et ouvriers qualifiés – Masse salariale'},
                {'label': 'Employés, manœuvres, ouvriers et apprentis – Masse salariale'},
                {'label': 'TOTAL (2)'},
                {'label': 'TOTAL (1+2)'},
                {'label': 'TOTAL (1+2)'},
            ],
        },
    ],
    'NOTE_29': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': 'Intérêts des emprunts'},
                {'label': 'Intérêts dans lloyers de locations acquisition'},
                {'label': 'Escompte accordés'},
                {'label': 'Autres intérêts'},
                {'label': 'Escomptes des effets de commerce'},
                {'label': 'Perte de change'},
                {'label': 'Pertes sur cessions des titres de placements'},
                {'label': "Malis provenant d'attribution gratuite d'actions au personnel dalarié et au personnel dirigeants"},
                {'label': 'Pertes sur risques financiers'},
                {'label': 'Charges pour dépreciation et provision à court terme à caracteres financiers'},
                {'label': 'TOTAL : FRAIS FINANCIERS'},
                {'label': 'Intérêts des prêts et creances diverse'},
                {'label': 'Revenus de participations'},
                {'label': 'Escomptes obtenus'},
                {'label': 'Revenus de placement'},
                {'label': 'Intérêts dans loyers de locations acquisition'},
                {'label': 'Gains de change'},
                {'label': 'Gains sur cessions de titres de placement'},
                {'label': 'Gains sur risques financiers'},
                {'label': 'Reprises de charges pour dépreciation et provision à court terme à caracteres financiers'},
                {'label': 'TOTAL REVENUS FINANCIERS'},
            ],
        },
    ],
    'NOTE_34': [
        {
            "title": None,
            "columns": ['Valeur'],
            "question": True,
            "rows": [
                {'label': 'Note renseignée ?'},
            ],
        },
        {
            "title": None,
            "columns": ['N', 'N-1'],
            "rows": [
                {'label': "Chiffre d'affaires"},
                {'label': 'Marge commerciale'},
                {'label': 'Valeur ajoutée'},
                {'label': "Excédent brut d'exploitation (EBE)"},
                {'label': "Résultat d'exploitation"},
                {'label': 'Résultat financier'},
                {'label': 'Résultat des activités ordinaires'},
                {'label': 'Résultat hors activités ordinaires'},
                {'label': 'Résultat net'},
                {'label': "Excédent brut d'exploitation (EBE)"},
                {'label': "- Valeurs comptables des cessions courantes d'immobilisations"},
                {'label': "+ Produits des cessions courantes d'immobilisations"},
                {'label': "= CAPACITE D'AUTOFINANCEMENT D'EXPLOITATION"},
                {'label': '+ Revenus financiers'},
                {'label': '+ Gains de charge'},
                {'label': '+ Transferts de charges financières'},
                {'label': '+ Produits HAO'},
                {'label': '+ Transferts de charges HAO'},
                {'label': '- Frais financiers'},
                {'label': '- Pertes de change'},
                {'label': '- Autres charges HAO'},
                {'label': '- Participations des travailleurs'},
                {'label': '- Impôts sur les résultats'},
                {'label': "= CAPACITES D'AUTOFINANCEMENT GLOBALE (CAFG)"},
                {'label': "- Distributions de dividendes opérées durant l'exercice"},
                {'label': '= AUTOFINANCEMENT'},
                {'label': "Rentabilité économique = Résultat d'exploitation (a)/capitaux propres + dettes financiers"},
                {'label': 'Rentabilité financière = Résultat net / Capitaux propres'},
                {'label': '+ Capitaux propres et ressources assimilées'},
                {'label': '+ Dettes financières et autres ressources assimilées'},
                {'label': '= Ressources stables'},
                {'label': '- Actif immobilisé'},
                {'label': '= FONDS DE ROULEMENT (1)'},
                {'label': "+ Actif circulant d'exploitation"},
                {'label': "- Passif circulant d'exploiatation"},
                {'label': "= BESOIN DE FINANCEMENT D'EXPLOITATION"},
                {'label': '+ Actif circulant HAO'},
                {'label': '- Passif circulant HAO'},
                {'label': '= BESOIN DE FINANCEMENT HAO'},
                {'label': 'BESOIN DE FINANCEMENT GLOBALE'},
                {'label': 'TRESORERIE NETTE'},
                {'label': 'CONTROLE TRERERIE NETTE'},
                {'label': 'Flux de trésorerie des activités opérationnelles'},
                {'label': "- Flux de trésorerie des activités d'investissements"},
                {'label': '+ Flux de trésorerie des activités de financement'},
                {'label': '= VARIATION DE LA TRESORERIE NETTE DE LA PERIODE'},
                {'label': 'Endettement financier brut'},
                {'label': '- Trésorerie - actif'},
                {'label': '= ENDETTEMENT FINANCIER NET'},
            ],
        },
    ],
    'TRACE': [
        {
            "title": None,
            "columns": ['Valeur'],
            "rows": [
                {'label': "Nom et Prénoms de l'opérateur"},
                {'label': 'Date de sasie'},
                {'label': 'Heure de fin de la saisie'},
            ],
        },
    ],
}
